name: Task 3 - Chuck norris awesomeness.

on:
  workflow_dispatch:

jobs:
  lint:
    name: Chuck norris awesomeness job
    runs-on: ubuntu-latest
    steps:
      - name: Fetch quote
        uses: fjogeleit/http-request-action@v1
        id: getQuoteResponse
        with:
          url: 'https://api.chucknorris.io/jokes/random'
          method: 'GET'
      - name: Show Response
        id: quote
        run: |
          echo "::set-output name=QUOTE::${{ fromJson(steps.getQuoteResponse.outputs.response).value }}"     
      - name: Run Chuck 
        uses: fjogeleit/http-request-action@v1
        with: 
          url: 'https://chuck.alexc.no/api/quote'
          method: 'POST'
          data: | 
            { "quote": "Fusce semper, urna a tempor aliquam, justo neque mollis massa, vel aliquet nisi lacus at ligula. Duis in nunc non odio pharetra iaculis a quis urna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut ac lectus semper tellus lacinia porta nec nec sem. Quisque ornare nibh convallis purus sodales lacinia. Morbi pulvinar vehicula feugiat. Sed interdum felis et est viverra gravida. Cras ac posuere quam. Integer ultricies ligula quis neque posuere, et vehicula risus malesuada. Sed vel nisi nec dolor viverra pellentesque ac at leo. Phasellus eu est ac ligula fermentum venenatis id at felis. Curabitur non aliquet velit. Donec neque orci, hendrerit at sapien in, lobortis scelerisque ante. Phasellus tempus lacus est, sit amet luctus lectus eleifend et. Ut ut interdum diam. Praesent sit amet pellentesque dui. Morbi volutpat hendrerit finibus. Sed rhoncus, lorem sit amet venenatis mollis, augue risus tempor tellus, id condimentum ex ante non nisl. Curabitur luctus elementum accumsan. Nunc aliquet magna sit amet nisl finibus fermentum. Sed elementum convallis dapibus. Curabitur ornare ipsum dolor, quis lobortis nunc hendrerit at. Cras aliquet felis in quam congue faucibus. Nunc posuere id sapien eget tempus. Morbi vehicula viverra pulvinar. Donec laoreet suscipit ligula at tristique. Fusce semper, urna a tempor aliquam, justo neque mollis massa, vel aliquet nisi lacus at ligula. Duis in nunc non odio pharetra iaculis a quis urna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut ac lectus semper tellus lacinia porta nec nec sem. Quisque ornare nibh convallis purus sodales lacinia. Morbi pulvinar vehicula feugiat. Sed interdum felis et est viverra gravida. Cras ac posuere quam. Integer ultricies ligula quis neque posuere, et vehicula risus malesuada. Sed vel nisi nec dolor viverra pellentesque ac at leo. Phasellus eu est ac ligula fermentum venenatis id at felis. Curabitur non aliquet velit. Donec neque orci, hendrerit at sapien in, lobortis scelerisque ante. Phasellus tempus lacus est, sit amet luctus lectus eleifend et. Ut ut interdum diam. Praesent sit amet pellentesque dui. Morbi volutpat hendrerit finibus. Sed rhoncus, lorem sit amet venenatis mollis, augue risus tempor tellus, id condimentum ex ante non nisl. Curabitur luctus elementum accumsan. Nunc aliquet magna sit amet nisl finibus fermentum. Sed elementum convallis dapibus. Curabitur ornare ipsum dolor, quis lobortis nunc hendrerit at. Cras aliquet felis in quam congue faucibus. Nunc posuere id sapien eget tempus. Morbi vehicula viverra pulvinar. Donec laoreet suscipit ligula at tristique.", "accessCode": "${{ secrets.CHUCK_NORRIS }}" }

      
