name: Task 3 - Chuck norris awesomeness.

on:
  workflow_dispatch:

jobs:
  lint:
    name: Chuck norris awesomeness job
    runs-on: ubuntu-latest
    steps:
      - name: Fetch quote
        uses: fjogeleit/http-request-action@v1
        id: getQuoteResponse
        with:
          url: 'https://api.chucknorris.io/jokes/random'
          method: 'GET'
      - name: Show Response
        id: quote
        run: |
          echo "::set-output name=QUOTE::${{ fromJson(steps.getQuoteResponse.outputs.response).value }}"     
      - name: Run Chuck 
        uses: fjogeleit/http-request-action@v1
        with: 
          url: 'https://chuck.alexc.no/api/quote'
          method: 'POST'
          data: | 
            { "quote": "${{ steps.quote.outputs }}", "accessCode": "${{ secrets.CHUCK_NORRIS }}" }

      
